
rule all:
    """
    The rule that runs all the rules.
    Ask Snakemake to say hello to the universe.
    """
    input: "hello_universe.txt"

rule hello_world:
    """
    Say hello to the world.
    """
    input: "world.txt"
    output: "hello_world.txt"
    shell:
        " echo 'Hello' |  cat - {input} > {output} "

rule hello_universe:
    """
    Say hello to the world - err, make that the universe.
    """
    input: "hello_world.txt"
    output: "hello_universe.txt"
    shell:
        "sed 's/world/universe/' {input} > {output} "

